title: Machine Learning en Aplicaciones Espaciales
subtitle: Posgrado en Big Data e inteligencia territorial - FLACSO
description: Materiales del curso       
show_downloads: true
theme: jekyll-theme-cayman