title: Fundamentos de Machine Learning
subtitle: Diploma en Ciencias Sociales Computacionales y Humanidades digitales - EIDAES
description: Materiales del curso       
show_downloads: true
theme: jekyll-theme-cayman
