title: "Módulo 4. Fundamentos de Machine Learning"
description: "Diplomatura en Ciencias Sociales Computacionales y Humanidades Digitales - EIDAES"
show_downloads: true
theme: jekyll-theme-minimal

