title: Introducción al aprendizaje automático
subtitle: Diplomatura en ciencias sociales computacionales y humanidades digitales
description: Materiales del curso       
show_downloads: false
theme: jekyll-theme-cayman
