title: Introducción (simple) a Machine Learning
subtitle: Imputando datos perdidos en la Encuesta Permanente de Hogares
description: Materiales del taller en las 2das. Jornadas de Big Data en Ciencias Económicas en la FCE - UNC
show_downloads: true
