#librerías módulo 4
library(tidyverse)
library(eph)
library(tidymodels)
library(themis)
library(vip)
library(baguette)
library(rpart.plot)
library(rules)
library(xgboost)
library(patchwork)
library(GDAtools)
library(FactoMineR)
library(factoextra)
library(ggrepel)
library(ggdendro)