---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list = ls())
```

# Librerias

```{r}
library(tidyverse)
library(caret)
library(rpart)
library(GGally)
library(MLmetrics)
library(pdp)
library(ISLR)
```

# Dataset

```{r}
data(Default)
df=Default
df = Default %>% mutate(default=factor(default))
head(df)
```

# Exploraci贸n

```{r}
ggpairs(df, aes(colour = default, alpha = 0.4), progress = FALSE)
```

D

# Train/Test split

```{r}
set.seed(282)
tr_index <- createDataPartition(y=df$default,
                                p=0.8,
                                list=FALSE)

train <- df[tr_index,]
test <- df[-tr_index,]
```

# Random Forest con CV

```{r}
set.seed(655)

rf_trControl <- trainControl(
        method="cv",
        number=5,
        # summaryFunction y ClassProbs son necesarios para calcular AUC
        summaryFunction=twoClassSummary, # multiClassSummary par mas de dos clases
        classProbs=TRUE
        )

rf_grid <- expand.grid(mtry=1:length(df) - 1,
                       min.node.size=c(5,10,15,20),
                       splitrule='gini' # variance para regresi贸n
                       )

model_weights <- ifelse(train$default == "No",
                        (1/table(train$default)[1]) * 0.5,
                        (1/table(train$default)[2]) * 0.5)

t0 <- proc.time()
rf_fit <-  caret::train(default ~ . , 
                 data = train, 
                 method = "ranger",
                 metric="AUC",
                 weights=model_weights,
                 trControl = rf_trControl,
                 tuneGrid = rf_grid,
                 importance='impurity' # Necesario para el feature importance
                 )
proc.time() -  t0
```

```{r}
rf_fit
```

# Evaluaci贸n

```{r}
caret::confusionMatrix(test$default, predict(rf_fit, test), mode="everything")
```

# Interpretaci贸n

```{r}
ggplot(varImp(rf_fit)) +
        theme_minimal()
```

```{r}
varimp <- function(data, y, model, loss='mse'){
        bool <- !(names(data) %in% y)
        X <- data[,bool]
        predic <- iml::Predictor$new(model, data=X, y=data[y])
        vi <- iml::FeatureImp$new(predic, loss=loss)
        return(vi)
}
```

```{r}
ggpubr::ggarrange(
        plot(varimp(data=train, y='default', model=rf_fit, loss="ce")),
        plot(varimp(data=test, y='default', model=rf_fit, loss="ce"))
        )
```

```{r}
ggpubr::ggarrange(
        partial(rf_fit, pred.var='balance', prob=TRUE,
                plot=TRUE, ice=TRUE, rug=TRUE,
                plot.engine = 'ggplot', alpha=0.1) + theme_minimal(),
        partial(rf_fit, pred.var='income', prob=TRUE,
                plot=TRUE, ice=TRUE, rug=TRUE, 
                plot.engine = 'ggplot', alpha=0.1) + theme_minimal(),
        partial(rf_fit, pred.var='student', prob=TRUE,
                plot=TRUE, ice=TRUE, rug=TRUE, 
                plot.engine = 'ggplot', alpha=0.1) + theme_minimal()
)
```
